### ISSUE TITLE
API ima napačne parametre

### ISSUE THREAD

**Issue by ilion227** [zejn/arsoapi#5]
Klic na povezavo [vreme/report/](https://opendata.si/vreme/report/) vrne:
```
{
    "status": "fail",
    "error": "Invalid parameters."
}
```

**Comment by zejn** [comment]
Podati moraš parametre za koordinato. Piše v readme, na prvi strani projekta: https://github.com/zejn/arsoapi#vreme-na-dolo%C4%8Denih-koordinatah
