### ISSUE TITLE
Stran z apijem ne deluje?

### ISSUE THREAD

**Issue by marksev1** [zejn/arsoapi#6]
Živjo,

kakšen je potem format url-ja da se dobim odgovor, takole ni prav: https://opendata.si/vreme/report/46.051418,14.505971/   :).

**Comment by zejn** [comment]
Npr. https://opendata.si/vreme/report/?lat=47.05&lon=12.92
Sem dodal v dokumentacijo.

**Comment by marksev1** [comment]
Hvala :). Sem našel vmes sicer že na tvojem twitterju :).
