### ISSUE TITLE
404 page - varnostni problem

### ISSUE THREAD

**Issue by zigcccc** [zejn/arsoapi#7]
Zdravo,

predkratkim uporabil vaš API, stran ki ne obstaja (npr. http://opendata.si/vreme/report) vrne debug error screen. V Django settings.py datoteki imate možnost, da izklopite debug mode `DEBUG = False`. Vredno popravka. 
![logo]

[logo]: https://i.imgur.com/x99Uwdn.png

**Comment by zejn** [comment]
Onemogočeno na produkciji, pametno pa bi bilo še dodat 404 page.
Hvala!
